version: '3'

services:
  database:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      TZ: 'America/Santiago'
      PGTZ: 'America/Santiago'
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    container_name: economy-game-db
    volumes:
      - ./postgres:/var/lib/postgresql/data