@domain = localhost:3000
@token = token

### LOGIN 
POST http://{{domain}}/auth/login
Content-Type: application/json

{
  "email": "asd@asd.com",
  //"personalNumberId": "11111111-1",
  "password": "asdasd123"
}

### LOGOUT
POST http://{{domain}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}

### VERIFY TOKEN
POST http://{{domain}}/auth/token
Content-Type: application/json
Authorization: Bearer {{token}}

### RENEW TOKEN
POST http://{{domain}}/auth/token/renew
Content-Type: application/json
Authorization: Bearer {{token}}