@domain = localhost:3000
@token = token
@recoverToken = token

### LOGIN 
POST http://{{domain}}/auth/login
Content-Type: application/json

{
  "email": "testing@economygame.com",
  //"personalNumberId": "11111111-1",
  "password": "this-is-a-password"
}

### LOGOUT
POST http://{{domain}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{token}}

### VERIFY TOKEN
POST http://{{domain}}/auth/token
Content-Type: application/json
Authorization: Bearer {{token}}

### RENEW TOKEN
POST http://{{domain}}/auth/token/renew
Content-Type: application/json
Authorization: Bearer {{token}}

### PASSWORD RECOVERY - PASSTOKEN REQUEST
POST http://{{domain}}/auth/password/recover
Content-Type: application/json

{
  "email": "testing@economygame.com"
}

### PASSWORD RECOVERY - CHANGE PASSWORD
POST http://{{domain}}/auth/password/change
Content-Type: application/json

{
  "key": "{{recoverToken}}",
  "newPassword": "newPassword-123"
}
