export enum EEnvironmentVars {
  NODE_ENV = 'NODE_ENV',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASS = 'DATABASE_PASS',
  DATABASE_NAME = 'DATABASE_NAME',
  JWT_SECRET = 'JWT_SECRET',

  SMTP_SERVER = 'SMTP_SERVER',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_USER_MAIL = 'SMTP_USER_MAIL',
  SMTP_USER_NAME = 'SMTP_USER_NAME',
  SMTP_USER_PASS = 'SMTP_USER_PASS',
}
